services:
  backend:
    build: ./backend/
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/home/bouzuya/bbna
      - backend-cargo-build-target:/home/bouzuya/bbna/backend/target

volumes:
  backend-cargo-build-target:
